# Dhanam - Community Wealth Management Platform
# Deploy via Enclii

apiVersion: enclii.dev/v1
kind: Service
metadata:
  name: dhanam
  project: madfam-platform
  description: Community wealth management with AI-powered insights

spec:
  build:
    type: dockerfile
    dockerfile: apps/web/Dockerfile
    context: .
    args:
      NEXT_PUBLIC_API_URL: https://api.dhan.am/v1
      NEXT_PUBLIC_BASE_URL: https://app.dhan.am
      NEXT_PUBLIC_OIDC_ISSUER: https://auth.madfam.io
      NEXT_PUBLIC_OIDC_CLIENT_ID: jnc_uE2zp9ume_Fd6jMl1elL6wqjiECM711t
      NEXT_PUBLIC_JANUA_API_URL: https://auth.madfam.io
    source:
      git:
        repository: https://github.com/madfam-org/dhanam
        branch: main
        autoDeploy: true

  runtime:
    port: 3000
    replicas: 2
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1Gi"

    healthCheck: /api/health
    readinessProbe:
      path: /api/health
      initialDelaySeconds: 10
      periodSeconds: 5
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3
    livenessProbe:
      path: /api/health
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 3

  env:
    - name: PORT
      value: "3000"
    - name: NODE_ENV
      value: production
    # Next.js public env vars (baked at build time)
    - name: NEXT_PUBLIC_API_URL
      value: https://api.dhan.am/v1
    - name: NEXT_PUBLIC_BASE_URL
      value: https://app.dhan.am

    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: dhanam-secrets
          key: database-url

    - name: REDIS_URL
      valueFrom:
        secretKeyRef:
          name: dhanam-secrets
          key: redis-url

    # Janua SSO - API URL for OAuth flows
    - name: NEXT_PUBLIC_JANUA_API_URL
      value: https://api.janua.dev
    # OIDC Configuration
    - name: NEXT_PUBLIC_OIDC_ISSUER
      value: https://auth.madfam.io
    - name: NEXT_PUBLIC_OIDC_CLIENT_ID
      value: jnc_uE2zp9ume_Fd6jMl1elL6wqjiECM711t
    - name: OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: dhanam-secrets
          key: janua-client-secret

    # MADFAM Analytics
    - name: NEXT_PUBLIC_ANALYTICS_URL
      value: https://analytics.madfam.io
    - name: NEXT_PUBLIC_ANALYTICS_SITE_ID
      value: dhanam

    # Coforma Feedback
    - name: NEXT_PUBLIC_COFORMA_URL
      value: https://coforma.madfam.io
    - name: NEXT_PUBLIC_COFORMA_PRODUCT_ID
      value: dhanam

    # AI Provider
    - name: OPENAI_API_KEY
      valueFrom:
        secretKeyRef:
          name: dhanam-secrets
          key: openai-api-key

    # Error Monitoring
    - name: SENTRY_DSN
      valueFrom:
        secretKeyRef:
          name: dhanam-secrets
          key: sentry-dsn
    - name: SENTRY_RELEASE
      value: dhanam-web@latest

  domains:
    # Production domain (primary)
    - domain: app.dhan.am
      tls: true
      tlsIssuer: cloudflare
      primary: true
    # Admin subdomain (same deployment, subdomain-based routing in middleware)
    - domain: admin.dhan.am
      tls: true
      tlsIssuer: cloudflare
    # Internal MADFAM domain (secondary)
    - domain: dhanam.madfam.io
      tls: true
      tlsIssuer: cloudflare
    # Landing / SEO domain (apex)
    - domain: dhan.am
      tls: true
      tlsIssuer: cloudflare
    # Landing / SEO domain (www → 301 redirect to apex via middleware)
    - domain: www.dhan.am
      tls: true
      tlsIssuer: cloudflare
      redirectTo: dhan.am

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 8
    targetCPUUtilizationPercentage: 70

  slo:
    availability: 99.9
    latencyP95: 300
    errorRate: 0.5
