---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dhanam-billing-secrets
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: dhanam-billing-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: secret/dhanam/staging/billing
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dhanam-provider-secrets
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: dhanam-provider-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: secret/dhanam/staging/provider
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dhanam-janua-secrets
  labels:
    app.kubernetes.io/managed-by: enclii
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: dhanam-janua-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: secret/dhanam/staging/janua
