apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dhanam-janua-secrets
spec:
  # Source secret: enclii/dhanam-staging-janua-source.
  dataFrom:
    - extract:
        key: dhanam-staging-janua-source
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
