import { PrismaClient, GoalActivityAction } from '../../../generated/prisma';
import { subDays } from 'date-fns';
import { SeedContext, randomDate } from '../helpers';

export async function seedAuditLogs(prisma: PrismaClient, ctx: SeedContext) {
  // 5. AUDIT LOGS
  console.log('\n📝 Creating audit logs...');

  await prisma.auditLog.createMany({
    data: [
      {
        userId: ctx.mariaUser.id,
        action: 'user.login',
        metadata: JSON.stringify({ ip: '192.168.1.100', userAgent: 'Chrome' }),
        ipAddress: '192.168.1.100',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.mariaUser.id,
        action: 'account.connected',
        metadata: JSON.stringify({ provider: 'belvo', accountId: 'maria-bbva-checking' }),
        ipAddress: '192.168.1.100',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.carlosUser.id,
        action: 'totp.enabled',
        metadata: null,
        ipAddress: '192.168.1.100',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.carlosUser.id,
        action: 'budget.created',
        metadata: JSON.stringify({ budgetId: 'q1-2024' }),
        ipAddress: '192.168.1.100',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.adminUser.id,
        action: 'space.created',
        metadata: JSON.stringify({ spaceName: 'TechCorp México' }),
        ipAddress: '192.168.1.100',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.adminUser.id,
        action: 'user.invite_sent',
        metadata: JSON.stringify({ email: 'cfo@techcorp.com' }),
        ipAddress: '192.168.1.100',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.platformAdmin.id,
        action: 'admin.user_view',
        metadata: JSON.stringify({ viewedUserId: ctx.mariaUser.id }),
        ipAddress: '192.168.1.100',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.platformAdmin.id,
        action: 'admin.feature_flag_toggle',
        metadata: JSON.stringify({ flag: 'ai_categorization', enabled: true }),
        ipAddress: '192.168.1.100',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      // Diego audit logs
      {
        userId: ctx.diegoUser.id,
        action: 'account.connected',
        metadata: JSON.stringify({ provider: 'blockchain', accountId: 'diego-btc-wallet' }),
        ipAddress: '10.0.1.50',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.diegoUser.id,
        action: 'account.connected',
        metadata: JSON.stringify({ provider: 'blockchain', accountId: 'diego-defi-arbitrum' }),
        ipAddress: '10.0.1.50',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.diegoUser.id,
        action: 'order.created',
        metadata: JSON.stringify({ assetSymbol: 'BTC', type: 'stop_loss', targetPrice: 55000 }),
        ipAddress: '10.0.1.50',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.diegoUser.id,
        action: 'order.executed',
        metadata: JSON.stringify({
          assetSymbol: 'BTC',
          type: 'dca',
          amount: 1000,
          currency: 'MXN',
        }),
        ipAddress: '10.0.1.50',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.diegoUser.id,
        action: 'esg.viewed',
        metadata: JSON.stringify({ tokens: ['ETH', 'SOL', 'AXS', 'SAND'] }),
        ipAddress: '10.0.1.50',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.diegoUser.id,
        action: 'user.login',
        metadata: JSON.stringify({ ip: '10.0.1.50', userAgent: 'Chrome' }),
        ipAddress: '10.0.1.50',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.diegoUser.id,
        action: 'order.created',
        metadata: JSON.stringify({ assetSymbol: 'SAND', type: 'oco' }),
        ipAddress: '10.0.1.50',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.diegoUser.id,
        action: 'account.connected',
        metadata: JSON.stringify({ provider: 'blockchain', accountId: 'diego-defi-base' }),
        ipAddress: '10.0.1.50',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      // Patricia audit logs
      {
        userId: ctx.adminUser.id,
        action: 'report.generated',
        metadata: JSON.stringify({ reportType: 'monthly_summary', period: '2026-01' }),
        ipAddress: '192.168.1.200',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.adminUser.id,
        action: 'space.settings_changed',
        metadata: JSON.stringify({
          spaceName: 'TechCorp México',
          changed: ['currency', 'timezone'],
        }),
        ipAddress: '192.168.1.200',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.adminUser.id,
        action: 'budget.updated',
        metadata: JSON.stringify({
          budgetName: 'Annual 2024',
          changes: ['R&D +200K', 'Travel -50K'],
        }),
        ipAddress: '192.168.1.200',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.adminUser.id,
        action: 'user.login',
        metadata: JSON.stringify({ ip: '192.168.1.200', userAgent: 'Safari', device: 'iPad Pro' }),
        ipAddress: '192.168.1.200',
        userAgent: 'Mozilla/5.0 (iPad; CPU OS 17_0)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.adminUser.id,
        action: 'report.generated',
        metadata: JSON.stringify({ reportType: 'tax_summary', year: 2025 }),
        ipAddress: '192.168.1.200',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.adminUser.id,
        action: 'account.connected',
        metadata: JSON.stringify({ provider: 'plaid', accountId: 'enterprise-chase' }),
        ipAddress: '192.168.1.200',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      // Carlos audit logs
      {
        userId: ctx.carlosUser.id,
        action: 'asset.added',
        metadata: JSON.stringify({ assetName: '1967 VW Beetle', type: 'vehicle' }),
        ipAddress: '192.168.1.150',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.carlosUser.id,
        action: 'goal.created',
        metadata: JSON.stringify({ goalName: 'Second Restaurant Location', target: 1500000 }),
        ipAddress: '192.168.1.150',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.carlosUser.id,
        action: 'transaction.split',
        metadata: JSON.stringify({ description: 'Costco Groceries', splitWith: 'Patricia' }),
        ipAddress: '192.168.1.150',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.carlosUser.id,
        action: 'user.login',
        metadata: JSON.stringify({ ip: '192.168.1.150', userAgent: 'Chrome' }),
        ipAddress: '192.168.1.150',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.carlosUser.id,
        action: 'budget.created',
        metadata: JSON.stringify({ budgetName: 'Q2 2024 Business' }),
        ipAddress: '192.168.1.150',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.carlosUser.id,
        action: 'asset.added',
        metadata: JSON.stringify({ assetName: 'Wine Collection', type: 'collectible' }),
        ipAddress: '192.168.1.150',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      // Maria audit logs
      {
        userId: ctx.mariaUser.id,
        action: 'goal.shared',
        metadata: JSON.stringify({ goalName: 'Family Trip to Europe', sharedWith: 'Guest User' }),
        ipAddress: '192.168.1.100',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.mariaUser.id,
        action: 'category.corrected',
        metadata: JSON.stringify({ merchant: 'Uber Eats', from: 'Transport', to: 'Food & Dining' }),
        ipAddress: '192.168.1.100',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.mariaUser.id,
        action: 'subscription.cancelled',
        metadata: JSON.stringify({
          service: 'Gym - Sports World',
          reason: 'Switched to outdoor running',
        }),
        ipAddress: '192.168.1.100',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.mariaUser.id,
        action: 'user.login',
        metadata: JSON.stringify({ ip: '192.168.1.100', userAgent: 'Safari', device: 'iPhone 15' }),
        ipAddress: '192.168.1.100',
        userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.mariaUser.id,
        action: 'budget.updated',
        metadata: JSON.stringify({ changes: ['Entertainment +500', 'Savings -500'] }),
        ipAddress: '192.168.1.100',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      // Guest (Life Beat) audit logs
      {
        userId: ctx.guestUser.id,
        action: 'life_beat.responded',
        metadata: JSON.stringify({ alertLevel: 30, channel: 'email' }),
        ipAddress: '192.168.1.50',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.guestUser.id,
        action: 'executor.assigned',
        metadata: JSON.stringify({ executor: 'Maria González', priority: 1 }),
        ipAddress: '192.168.1.50',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.guestUser.id,
        action: 'will.reviewed',
        metadata: JSON.stringify({ lastReview: '2025-12-01' }),
        ipAddress: '192.168.1.50',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.guestUser.id,
        action: 'user.login',
        metadata: JSON.stringify({ ip: '192.168.1.50', userAgent: 'Chrome' }),
        ipAddress: '192.168.1.50',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      // Platform Admin audit logs
      {
        userId: ctx.platformAdmin.id,
        action: 'admin.impersonation',
        metadata: JSON.stringify({
          impersonatedUser: ctx.mariaUser.id,
          reason: 'Support ticket #4521',
        }),
        ipAddress: '10.0.0.1',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.platformAdmin.id,
        action: 'admin.user_search',
        metadata: JSON.stringify({ query: 'carlos@dhanam.demo' }),
        ipAddress: '10.0.0.1',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.platformAdmin.id,
        action: 'admin.audit_export',
        metadata: JSON.stringify({ dateRange: '2025-12-01 to 2026-01-01', format: 'csv' }),
        ipAddress: '10.0.0.1',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.platformAdmin.id,
        action: 'admin.user_view',
        metadata: JSON.stringify({ viewedUserId: ctx.diegoUser.id }),
        ipAddress: '10.0.0.1',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.platformAdmin.id,
        action: 'admin.feature_flag_toggle',
        metadata: JSON.stringify({ flag: 'gaming_dashboard', enabled: true }),
        ipAddress: '10.0.0.1',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
      {
        userId: ctx.platformAdmin.id,
        action: 'admin.user_search',
        metadata: JSON.stringify({ query: 'diego@dhanam.demo' }),
        ipAddress: '10.0.0.1',
        userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
        timestamp: randomDate(subDays(new Date(), 30), new Date()),
      },
    ],
  });
}
