import { Body, Controller, Post, UseGuards } from '@nestjs/common';
import {
  ApiBearerAuth,
  ApiCreatedResponse,
  ApiOperation,
  ApiTags,
  ApiUnauthorizedResponse,
} from '@nestjs/swagger';
import { ConfigService } from '@nestjs/config';
import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayNotEmpty,
  IsArray,
  IsDateString,
  IsEmail,
  IsInt,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  Min,
} from 'class-validator';

import { CurrentUser } from '@core/auth/decorators/current-user.decorator';
import { JwtAuthGuard } from '@core/auth/guards/jwt-auth.guard';
import { PrismaService } from '@core/prisma/prisma.service';
import { ReportFormat } from '@db';
import { ReportArchiveService } from '@modules/analytics/report-archive.service';
import { ReportShareTokenService } from '@modules/analytics/report-share-token.service';
import { SavedReportService } from '@modules/analytics/saved-report.service';

import { EmailService } from './email.service';

class CreateInvestorReportPacketDto {
  @IsUUID()
  spaceId!: string;

  @IsDateString()
  startDate!: string;

  @IsDateString()
  endDate!: string;

  @IsArray()
  @ArrayNotEmpty()
  @ArrayMaxSize(25)
  @IsEmail({}, { each: true })
  recipients!: string[];

  @IsString()
  @IsOptional()
  name?: string;

  @IsString()
  @IsOptional()
  message?: string;

  @IsInt()
  @Min(1)
  @Max(720)
  @IsOptional()
  @Type(() => Number)
  expiresInHours?: number;
}

@ApiTags('Investor Reports')
@ApiBearerAuth()
@Controller('reports/investor-packets')
@UseGuards(JwtAuthGuard)
export class InvestorReportsController {
  constructor(
    private readonly savedReportService: SavedReportService,
    private readonly reportArchiveService: ReportArchiveService,
    private readonly shareTokenService: ReportShareTokenService,
    private readonly emailService: EmailService,
    private readonly prisma: PrismaService,
    private readonly config: ConfigService
  ) {}

  @Post()
  @ApiOperation({ summary: 'Generate, preserve, share, and email an investor report packet' })
  @ApiCreatedResponse({ description: 'Investor report packet generated and queued for delivery' })
  @ApiUnauthorizedResponse({ description: 'Invalid or missing JWT token' })
  async createPacket(
    @CurrentUser('id') userId: string,
    @Body() dto: CreateInvestorReportPacketDto
  ) {
    const reportName = dto.name || `Investor packet ${dto.startDate} to ${dto.endDate}`;
    const savedReport = await this.savedReportService.create(userId, {
      spaceId: dto.spaceId,
      name: reportName,
      description: 'Investor-facing financial packet generated by Dhanam',
      type: 'investor_packet',
      format: ReportFormat.pdf,
      filters: {
        startDate: dto.startDate,
        endDate: dto.endDate,
        audience: 'investors',
        recipients: dto.recipients,
      },
      enabled: true,
    });

    const [{ generatedReport, downloadUrl }, space, sender] = await Promise.all([
      this.reportArchiveService.generateAndArchive(savedReport.id, userId),
      this.prisma.space.findUnique({ where: { id: dto.spaceId }, select: { name: true } }),
      this.prisma.user.findUnique({ where: { id: userId }, select: { name: true, email: true } }),
    ]);

    const token = await this.shareTokenService.createToken(userId, savedReport.id, {
      expiresInHours: dto.expiresInHours || 168,
      generatedReportId: generatedReport.id,
    });
    const appUrl = this.config.get<string>('APP_URL') || 'https://app.dhan.am';
    const publicUrl = `${appUrl.replace(/\/$/, '')}/public/report/${token.token}`;
    const expiresAt = new Date(token.expiresAt).toISOString();

    await Promise.all(
      dto.recipients.map((recipient) =>
        this.emailService.sendEmail({
          to: recipient,
          subject: `Investor report ready: ${space?.name || 'Dhanam'}`,
          template: 'investor-report',
          priority: 'high',
          context: {
            recipient,
            reportName,
            spaceName: space?.name || 'Dhanam Space',
            senderName: sender?.name || sender?.email || 'Dhanam',
            senderEmail: sender?.email || '',
            startDate: dto.startDate,
            endDate: dto.endDate,
            message: dto.message,
            publicUrl,
            expiresAt,
          },
        })
      )
    );

    return {
      reportId: savedReport.id,
      generatedReportId: generatedReport.id,
      shareTokenId: token.id,
      reportName,
      publicUrl,
      ownerDownloadUrl: downloadUrl,
      expiresAt,
      recipientsQueued: dto.recipients.length,
    };
  }
}
