import { PrismaClient, Currency } from '../../../generated/prisma';
import { addDays, subDays } from 'date-fns';
import { SeedContext } from '../helpers';

export async function seedRecurringTransactions(prisma: PrismaClient, ctx: SeedContext) {
  // 2. RECURRING TRANSACTIONS (batch)
  console.log('\n🔄 Creating recurring transactions...');

  await prisma.recurringTransaction.createMany({
    data: [
      {
        spaceId: ctx.mariaSpace.id,
        merchantName: 'Rent Payment',
        expectedAmount: 15000,
        currency: Currency.MXN,
        frequency: 'monthly',
        status: 'confirmed',
        occurrenceCount: 12,
        confidence: 0.99,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 60),
      },
      {
        spaceId: ctx.mariaSpace.id,
        merchantName: 'Salary Deposit',
        expectedAmount: 42000,
        currency: Currency.MXN,
        frequency: 'biweekly',
        status: 'confirmed',
        occurrenceCount: 24,
        confidence: 0.98,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 60),
      },
      {
        spaceId: ctx.mariaSpace.id,
        merchantName: 'Gym Membership',
        expectedAmount: 899,
        currency: Currency.MXN,
        frequency: 'monthly',
        status: 'confirmed',
        occurrenceCount: 8,
        confidence: 0.95,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 60),
      },
      {
        spaceId: ctx.carlosPersonal.id,
        merchantName: 'Car Insurance',
        expectedAmount: 3500,
        currency: Currency.MXN,
        frequency: 'monthly',
        status: 'confirmed',
        occurrenceCount: 10,
        confidence: 0.97,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 60),
      },
      {
        spaceId: ctx.carlosPersonal.id,
        merchantName: 'Salary Deposit',
        expectedAmount: 65000,
        currency: Currency.MXN,
        frequency: 'biweekly',
        status: 'confirmed',
        occurrenceCount: 24,
        confidence: 0.99,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 60),
      },
      {
        spaceId: ctx.carlosBusiness.id,
        merchantName: 'Office Rent',
        expectedAmount: 35000,
        currency: Currency.MXN,
        frequency: 'monthly',
        status: 'confirmed',
        occurrenceCount: 12,
        confidence: 0.99,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 60),
      },
      {
        spaceId: ctx.carlosBusiness.id,
        merchantName: 'Business Loan Payment',
        expectedAmount: 18500,
        currency: Currency.MXN,
        frequency: 'monthly',
        status: 'confirmed',
        occurrenceCount: 10,
        confidence: 0.98,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 60),
      },
      {
        spaceId: ctx.diegoSpace.id,
        merchantName: 'Rent Payment',
        expectedAmount: 12000,
        currency: Currency.MXN,
        frequency: 'monthly',
        status: 'confirmed',
        occurrenceCount: 6,
        confidence: 0.99,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 60),
      },
      {
        spaceId: ctx.diegoSpace.id,
        merchantName: 'Cloud Hosting',
        expectedAmount: 49,
        currency: Currency.USD,
        frequency: 'monthly',
        status: 'confirmed',
        occurrenceCount: 8,
        confidence: 0.92,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 60),
      },
      {
        spaceId: ctx.diegoSpace.id,
        merchantName: 'Salary Deposit',
        expectedAmount: 38000,
        currency: Currency.MXN,
        frequency: 'weekly',
        status: 'confirmed',
        occurrenceCount: 18,
        confidence: 0.7,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 60),
      },
      {
        spaceId: ctx.diegoSpace.id,
        merchantName: 'LAND Rental - Parcel (-12, 45)',
        expectedAmount: 150,
        currency: Currency.USD,
        frequency: 'monthly',
        status: 'confirmed',
        occurrenceCount: 6,
        confidence: 0.88,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 45),
      },
      {
        spaceId: ctx.diegoSpace.id,
        merchantName: 'LAND Rental - Parcel (8, -22)',
        expectedAmount: 150,
        currency: Currency.USD,
        frequency: 'monthly',
        status: 'confirmed',
        occurrenceCount: 4,
        confidence: 0.85,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 30),
      },
      {
        spaceId: ctx.diegoSpace.id,
        merchantName: 'Sandbox Game Maker Revenue',
        expectedAmount: 320,
        currency: Currency.USD,
        frequency: 'monthly',
        status: 'confirmed',
        occurrenceCount: 3,
        confidence: 0.72,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 30),
      },
      {
        spaceId: ctx.diegoSpace.id,
        merchantName: 'Axie Scholarship Revenue',
        expectedAmount: 200,
        currency: Currency.USD,
        frequency: 'monthly',
        status: 'confirmed',
        occurrenceCount: 8,
        confidence: 0.82,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 60),
      },
      {
        spaceId: ctx.diegoSpace.id,
        merchantName: 'Gala Node Rewards',
        expectedAmount: 150,
        currency: Currency.USD,
        frequency: 'monthly',
        status: 'confirmed',
        occurrenceCount: 10,
        confidence: 0.9,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 90),
      },
      {
        spaceId: ctx.diegoSpace.id,
        merchantName: 'Illuvium Revenue Distribution',
        expectedAmount: 180,
        currency: Currency.USD,
        frequency: 'monthly',
        status: 'confirmed',
        occurrenceCount: 5,
        confidence: 0.78,
        lastOccurrence: subDays(new Date(), Math.floor(Math.random() * 30)),
        nextExpected: addDays(new Date(), Math.floor(Math.random() * 30) + 1),
        confirmedAt: subDays(new Date(), 45),
      },
    ],
  });

  console.log('  ✓ Created 10 recurring transactions');
}
